#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www 
# points to your load-balancer IP

info () {
    dom=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:'| tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $dom" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]; then
    info "$1" "www"
    info "$1" "lb-01"
    info "$1" "web-01"
    info "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    info "$1" "$2"
fi
