#!/usr/bin/env bash
# prints some data depending on whether a server request is sucessful or not


# handles only one argument passed
all () {
    domain="$1"
    list=("www" "lb-01" "web-01" "web-02")
    for sub in "${list[@]}"; do
        name="$sub.$domain"
        dig_name=$(dig "$name" | grep -A1 'ANSWER SECTION:')
        echo $dig_name | awk -v sub="$sub" '{print "The subdomain " sub " is a " $4 " record and points to " $5 ""}' $dig_name
    done
}


# handles a specific domain
specific () {
    domain="$1"
    subdomain="$2"
    if [[ "$subdomain" = "www" ]]; then
        dom="$subdomain.$domain"
        dig_dom=$(dig $dom | grep -A1 'ANSWER SECTION:')
        awk '{print "The subdomain www is a {$4} record and points to ${5}"}' dig_dom
    elif [[ "$subdomain" = "web-01" ]]; then
        dom=$subdomain + "." + $domain
        dig_dom=$(dig $dom | grep -A1 'ANSWER SECTION:')
        awk '{print "The subdomain web-01 is a {$4} record and points to ${5}"}' dig_dom
    elif [[ "$subdomain" = "web-02" ]]; then
        dom=$subdomain + "." + $domain
        dig_dom=$(dig $dom | grep -A1 'ANSWER SECTION:')
        awk '{print "The subdomain www is a {$4} record and points to ${5}"}' dig_dom
    elif [[ "$subdomain" = "lb-01" ]]; then 
        dom=$subdomain + "." + $domain
        dig_dom=$(dig $dom | grep -A1 'ANSWER SECTION:')
        awk '{print "The subdomain www is a {$4} record and points to ${5}"}' dig_dom
    else
        return
    fi
}

if [[ "$#" -eq 1 ]]; then
    all "$1"
else
   specific "$1" "$2"
fi

