#!/usr/bin/env bash
# installs nginx on a new ubuntu machine
# and adds a custom header

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
	index index.html index.htm;		

}" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
