#!/usr/bin/env bash
# installs and configures HAproxy on lb-01 server

sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9

sudo apt-get update
sudo apt-get install -y haproxy=2.9\*
sudo service haproxy start

# enable HAproxy so that it can start and stop with VPS
echo "ENABLED=1" >> sudo /etc/default/haproxy

# we make a copy of the daulthaproxy.cfg file:
sudo cp /etc/haproxy/haproxy.cfg{,.orig}

# we can now make changes to our copy
echo "global
	log /dev/log    local0
	log /dev/log    local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	mode http
	timeout client 30s
	timeout connect 10s
	timeout server 30s
	timeout http-request 10s
	log global
	option httplog
	maxconn 3000

frontend myfrontend
	bind *:80
	stats uri /haproxy?status
	default_backend alx_servers

backend alx_servers
	balance roundrobin
	server 437274-web-01 100.26.243.0:80 check
	server 437274-web-02 100.25.200.61:80 check

" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
