#!/usr/bin/env bash
# executes commands to a server from my local terminal

# scp -i ~/.ssh/school -o StrictHostKeyChecking=no "$1" ubuntu@34.207.62.172:~/
ssh ubuntu@34.207.62.172 -i ~/.ssh/school "$1" "$2"
