#!/usr/bin/env bash
# dumps databases to a file and compresses the file

sudo mysqldump -u root -p"$1" --all-databases | sudo tee backup.sql > /dev/null
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
