#!/usr/bin/env bash
# Pings an IP address passed as an argument:
# Accepts a string argument
# Displays an error if no argument is passed
# Ping the IP 5 times


if [[ "$#" -lt 1 ]]; then
 echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
 exit 1
else
	ping -c 5 "$1"
fi
