#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
#+display hours from 0 to 12
#+display minutes from 1 to 59

h=1
m=1
while [ "$h" -le 12 ]; do
echo "Hour: $h"

while [ "$m" -lt 60 ]; do
echo "$m"
m=$((m+1))
done

m=1
h=$((h+1))
done
