#!/usr/bin/env bash
# commands to a server from my local terminal

# for transferring the a file
# scp -i ~/.ssh/school -o StrictHostKeyChecking=no "$1" ubuntu@34.224.3.133:~
ssh ubuntu@34.224.3.133 -i ~/.ssh/school $1
